# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [52]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [56]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1, 2, 3])
type(arr1)

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr1.shape, arr2.shape)

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[4, 5, 6],
                  [7, 8, 9]],
                 [[10, 11, 12],
                  [13, 14, 15]]])
arr3.shape


(3,) (2, 3)


(2, 2, 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [60]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.shape, arr1.ndim, arr1.dtype, arr1.size, type(arr1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [61]:
# Attributes of 2-dimensional array
arr2.shape, arr2.ndim, arr2.dtype, arr2.size, type(arr2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [62]:
# Attributes of 3-dimensional array
arr3.shape, arr3.ndim, arr3.dtype, arr3.size, type(arr3)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [66]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df1 = pd.DataFrame(arr2,
                  index=['Sun', 'Mon'],
                  columns=['kills', 'hits', 'misses'])
df1

kills  hits  misses
Sun      1     2       3
Mon      4     5       6

In [68]:
# Create an array of shape (10, 2) with only ones
arr4 = np.ones((10, 2))
arr4

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [72]:
# Create an array of shape (7, 2, 3) of only zeros
arr5 = np.zeros((7, 2, 3))
arr5



array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [74]:
# Create an array within a range of 0 and 100 with step 3
arr6 = np.arange(0, 100, 3)
arr6

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [76]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr7 = np.random.randint(0, 10, size=(7, 2))
arr7

array([[1, 0],
       [7, 5],
       [0, 1],
       [5, 7],
       [2, 9],
       [8, 3],
       [5, 2]], dtype=int32)

In [79]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr8 = np.random.uniform(0, 1, size=(3, 5))
arr8

array([[0.59049614, 0.62346022, 0.53655598, 0.25367003, 0.80868389],
       [0.71144617, 0.85989237, 0.74738791, 0.96390149, 0.79958863],
       [0.64389226, 0.55893789, 0.97458855, 0.16890727, 0.01689107]])

In [84]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr9 = np.random.randint(0, 10, size=(4, 6))
arr9

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

Stay the same due to seeting the seed for the random number generator

In [94]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr10 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(arr10)


array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [95]:
arr10

array([[1, 4, 7, 2, 3, 1, 5],
       [1, 8, 1, 1, 2, 2, 6],
       [7, 5, 1, 1, 3, 2, 5]], dtype=int32)

In [96]:
# Find the 0'th index of the latest array you created
arr10[0]

array([1, 4, 7, 2, 3, 1, 5], dtype=int32)

In [97]:
# Get the first 2 rows of latest array you created
arr10[0:2]

array([[1, 4, 7, 2, 3, 1, 5],
       [1, 8, 1, 1, 2, 2, 6]], dtype=int32)

In [99]:
# Get the first 2 values of the first 2 rows of the latest array
arr10[0:2, 0:2]

array([[1, 4],
       [1, 8]], dtype=int32)

In [101]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr11 = np.random.randint(0, 10, size=(3, 5))
arr12 = np.ones((3, 5))
arr11

array([[8, 5, 2, 3, 3],
       [2, 9, 2, 2, 3],
       [6, 3, 8, 0, 7]], dtype=int32)

In [102]:
arr12

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [104]:
# Add the two arrays together
np.add(arr11, arr12)

array([[ 9.,  6.,  3.,  4.,  4.],
       [ 3., 10.,  3.,  3.,  4.],
       [ 7.,  4.,  9.,  1.,  8.]])

In [105]:
# Create another array of ones of shape (5, 3)
arr13 = np.ones((5, 3))
arr13

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [107]:
# Try add the array of ones and the other most recent array together
# np.add(arr12, arr13)
np.add(arr12, arr13.reshape((3, 5)))

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?
Arrays are not the same shape
How would you fix it? change the shape of the array to match


In [108]:
# Create another array of ones of shape (3, 5)
arr14 = np.ones((3, 5))
arr14

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [111]:
# Subtract the new array of ones from the other most recent array
np.subtract(arr14.reshape(5, 3), arr13)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [112]:
# Multiply the ones array with the latest array
np.multiply(arr14.reshape(5, 3), arr13)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [113]:
# Take the latest array to the power of 2 using '**'
arr11

array([[8, 5, 2, 3, 3],
       [2, 9, 2, 2, 3],
       [6, 3, 8, 0, 7]], dtype=int32)

In [116]:
arr15 = np.array([3, 3, 3, 3, 3])
arr15

array([3, 3, 3, 3, 3])

In [117]:
arr11 ** arr15

array([[512, 125,   8,  27,  27],
       [  8, 729,   8,   8,  27],
       [216,  27, 512,   0, 343]])

In [118]:
# Do the same thing with np.square()
np.square(arr11)

array([[64, 25,  4,  9,  9],
       [ 4, 81,  4,  4,  9],
       [36,  9, 64,  0, 49]], dtype=int32)

In [119]:
# Find the mean of the latest array using np.mean()
np.mean(arr11)

np.float64(4.2)

In [120]:
# Find the maximum of the latest array using np.max()
np.max(arr11)

np.int32(9)

In [121]:
# Find the minimum of the latest array using np.min()
np.min(arr11)

np.int32(0)

In [122]:
# Find the standard deviation of the latest array
np.std(arr11)

np.float64(2.663331247391757)

In [123]:
# Find the variance of the latest array
np.var(arr11)

np.float64(7.093333333333333)

In [124]:
# Reshape the latest array to (3, 5, 1)
arr11.reshape((3, 5, 1))

array([[[8],
        [5],
        [2],
        [3],
        [3]],

       [[2],
        [9],
        [2],
        [2],
        [3]],

       [[6],
        [3],
        [8],
        [0],
        [7]]], dtype=int32)

In [125]:
# Transpose the latest array
arr11.T

array([[8, 2, 6],
       [5, 9, 3],
       [2, 2, 8],
       [3, 2, 0],
       [3, 3, 7]], dtype=int32)

What does the transpose do?
Flips the axis, EG 5 rows and 3 cols becomes 3 rows and 5 cols.

In [127]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr16 = np.random.randint(0, 10, size=(3, 3))
arr17 = np.random.randint(0, 10, size=(3, 2))
arr16

array([[2, 6, 9],
       [8, 3, 0],
       [1, 0, 4]], dtype=int32)

In [128]:
arr17

array([[4, 6],
       [8, 8],
       [2, 2]], dtype=int32)

In [129]:
# Perform a dot product on the two newest arrays you create
np.dot(arr16, arr17)

array([[74, 78],
       [56, 72],
       [12, 14]], dtype=int32)

In [130]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr18 = np.random.randint(0, 10, size=(4, 3))
arr19 = np.random.randint(0, 10, size=(4, 3))
arr18

array([[2, 3, 7],
       [5, 7, 0],
       [7, 3, 0],
       [7, 3, 5]], dtype=int32)

In [132]:
arr19

array([[7, 3, 2],
       [8, 2, 8],
       [1, 1, 1],
       [5, 2, 8]], dtype=int32)

In [135]:
# Perform a dot product on the two newest arrays you created
#np.dot(arr18, arr19)
np.dot(arr18, arr19.reshape(3, 4))

array([[27, 65, 21, 75],
       [49, 71, 17, 47],
       [55, 45, 17, 59],
       [60, 70, 27, 99]], dtype=int32)

It doesn't work. How would you fix it?
reshape on of the arrays

In [136]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(arr18, arr19.T)

array([[ 37,  78,  12,  72],
       [ 56,  54,  12,  39],
       [ 58,  62,  10,  41],
       [ 68, 102,  15,  81]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this? Because now there shapes a complimentary allowing the dot product to work.

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [138]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr20 = np.random.randint(0, 10, size=(5, 3))
arr21 = np.random.randint(0, 10, size=(5, 3))
arr20

array([[0, 4, 5],
       [2, 8, 4],
       [7, 0, 4],
       [2, 0, 3],
       [4, 6, 0]], dtype=int32)

In [139]:
arr21

array([[2, 1, 8],
       [9, 5, 9],
       [2, 7, 7],
       [1, 5, 6],
       [1, 9, 1]], dtype=int32)

In [140]:
# Compare the two arrays with '>'
arr20 > arr21

array([[False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False]])

What happens when you compare the arrays with `>`? An array of booleans is returned showing the results of the comparison for each mirroring element in the arrays

In [142]:
# Compare the two arrays with '>='
arr20 >= arr21

array([[False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False]])

In [147]:
arr20

array([[0, 4, 5],
       [2, 8, 4],
       [7, 0, 4],
       [2, 0, 3],
       [4, 6, 0]], dtype=int32)

In [144]:
# Find which elements of the first array are greater than
np.greater(arr20, 4)

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False, False],
       [False,  True, False]])

In [146]:
np.argwhere(arr20 > 4)

array([[0, 2],
       [1, 1],
       [2, 0],
       [4, 1]])

In [149]:
arr20[arr20 > 4]

array([5, 8, 7, 6], dtype=int32)

In [150]:
# Which parts of each array are equal? (try using '==')
arr20 == arr21

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

## 

In [153]:
arr20

array([[0, 4, 5],
       [2, 8, 4],
       [7, 0, 4],
       [2, 0, 3],
       [4, 6, 0]], dtype=int32)

In [152]:
# Sort one of the arrays you just created in ascending order
np.sort(arr20)

array([[0, 4, 5],
       [2, 4, 8],
       [0, 4, 7],
       [0, 2, 3],
       [0, 4, 6]], dtype=int32)

In [155]:
np.sort(arr20, 0)

array([[0, 0, 0],
       [2, 0, 3],
       [2, 4, 4],
       [4, 6, 4],
       [7, 8, 5]], dtype=int32)

In [156]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr20)

array([[0, 1, 2],
       [0, 2, 1],
       [1, 2, 0],
       [1, 0, 2],
       [2, 0, 1]])

In [157]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr20)

np.int64(4)

In [158]:
arr20

array([[0, 4, 5],
       [2, 8, 4],
       [7, 0, 4],
       [2, 0, 3],
       [4, 6, 0]], dtype=int32)

In [159]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr20)

np.int64(0)

In [160]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr20, axis=1)

array([2, 1, 0, 2, 1])

In [161]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr20, axis=0)

array([0, 2, 4])

In [163]:
# Create an array of normally distributed random numbers
arr22 = np.random.uniform(0, 10, size=(5, 5))
arr22

array([[8.60404618, 2.50251361, 0.38834734, 3.03265515, 5.37082427],
       [3.26651242, 8.27869004, 2.71542916, 9.6525183 , 4.57265162],
       [8.42023075, 1.94380034, 4.11353905, 6.99512211, 1.38353092],
       [1.32745422, 9.69536867, 7.14595104, 0.41067517, 3.98820901],
       [4.33520738, 7.44042643, 2.50860527, 1.84333674, 0.80872967]])

In [165]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.